name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge Team tfvars Files
        run: |
          jq -s 'reduce .[] as $item ({}; . * $item) | {projects: .}' teams/*/project.tfvars.json > combined_projects.tfvars.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (No Refresh)
        env:
          TF_LOG: DEBUG
          TF_VAR_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          TF_VAR_region: "us-central1"
        run: terraform plan -no-color -refresh=false -var-file=combined_projects.tfvars.json
