name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Merge Script
        run: |
          chmod +x scripts/merge_tfvars.sh
          ./scripts/merge_tfvars.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (No Refresh)
        env:
          TF_LOG: DEBUG
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform plan -no-color -refresh=false -var-file=combined_projects.tfvars.json
